sudo: required

language: node_js
node_js:
  - node

before_install:
  - pip install awscli --upgrade --user
  - aws --version

script:
  - npm test

after_success:
  - npm run build
  - >
    aws s3 rm s3://lioneltay.com --recursive &&
    aws s3 cp ./dist s3://lioneltay.com --recursive &&
    aws cloudfront create-invalidation --distribution-id E1MWKWSMZFSYWH --paths /index.html
